[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
claim = "7jd5qzcXeDhppUbjycdE9FtZG46E4XQ69mwsns5gjYNW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/dev13pKnDpBiK5gPH3MUurzqgWx8vt2WkT7RvjLjoi3.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
